Repository deity-io/falcon, pull requests merged in 2018-10, with the labels that each got.

#68 Improving error handling (for deity/falcon-magento2-api package)
  package.json
  packages/falcon-client/src/index.js
  packages/falcon-dev-tools/eslint-config-falcon/package.json
  packages/falcon-errors/src/codes.js
  packages/falcon-magento2-api/package.json
  packages/falcon-magento2-api/src/Magento2ApiBase.js
  packages/falcon-magento2-api/src/index.test.js
Labels: improvement

#74 Fixing broken dependencies
  .eslintignore
  examples/shop-with-blog/client/.eslintignore
  examples/shop-with-blog/client/package.json
  package.json
  packages/falcon-dev-tools/eslint-config-falcon/package.json
Labels: bug

#73 DynamicRoute Extension migration
  examples/shop-with-blog/server/config/default.json
  examples/shop-with-blog/server/package.json
  package.json
  packages/falcon-dynamic-route-extension/README.md
  packages/falcon-dynamic-route-extension/package.json
  packages/falcon-dynamic-route-extension/schema.graphql
  packages/falcon-server-env/src/models/ApiDataSource.ts
  packages/falcon-server-env/src/models/Extension.ts
  packages/falcon-server-env/src/types.ts
  packages/falcon-server/README.md
  packages/falcon-server/docs/DynamicRouteResolver.md
  packages/falcon-server/docs/README.md
  packages/falcon-server/src/containers/ExtensionContainer.js
  packages/falcon-server/src/index.js
  packages/falcon-server/src/index.test.js
  packages/falcon-server/src/resolvers/DynamicRouteResolver.js
  packages/falcon-server/src/resolvers/DynamicRouteResolver.test.js
  packages/falcon-server/src/schema.graphql
  packages/falcon-shop-extension/src/index.js
Labels: enhancement

#81 ApolloClient config
  examples/shop-with-blog/client/config/custom-environment-variables.json
  examples/shop-with-blog/client/config/default.json
  packages/falcon-client/README.md
  packages/falcon-client/src/service/ApolloClient.js
  packages/falcon-client/src/service/ApolloClient.test.js
Labels: improvement

#83 improved error handling on invallid admin token
  packages/falcon-errors/src/codes.js
  packages/falcon-magento2-api/src/Magento2ApiBase.js
Labels: bug

#100 Fixing broken re-export statements in example
  packages/falcon-client/src/clientApp/index.js
Labels: bug

#89 Event flow
  examples/shop-with-blog/server/config/default.json
  packages/falcon-logger/index.d.ts
  packages/falcon-logger/src/index.d.ts
  packages/falcon-server-env/README.md
  packages/falcon-server-env/docs/README.md
  packages/falcon-server-env/package.json
  packages/falcon-server-env/src/models/ApiDataSource.ts
  packages/falcon-server/docs/README.md
  packages/falcon-server/src/containers/ApiContainer.js
  packages/falcon-server/src/containers/ApiContainer.test.js
  packages/falcon-server/src/containers/ExtensionContainer.js
  packages/falcon-server/src/containers/ExtensionContainer.test.js
  packages/falcon-server/src/events.js
  packages/falcon-server/src/index.js
Labels: feature, node

#98 Changing falcon-server config structure (apis, extensions)
  examples/shop-with-blog/server/config/default.json
  packages/falcon-server/docs/ApiContainer.md
  packages/falcon-server/docs/ExtensionContainer.md
  packages/falcon-server/src/containers/ApiContainer.js
  packages/falcon-server/src/containers/ApiContainer.test.js
  packages/falcon-server/src/containers/ExtensionContainer.js
  packages/falcon-server/src/containers/ExtensionContainer.test.js
Labels: extension, feature, node

#121 Moving renovate.json config file
  .github/.renovate.json
Labels: automation
