Repository deity-io/falcon, pull requests merged in 2018-11, with the labels that each got.

#117 Node 11 tests and "NIGHTLY_BUILD" hook
  .travis.yml
  lerna.json
  package.json
  packages/create-falcon-app/scripts/prepublish.js
  packages/create-falcon-app/src/index.js
  packages/falcon-server/src/resolvers/DynamicRouteResolver.js
  packages/falcon-server/src/resolvers/DynamicRouteResolver.test.js
Labels: feature, node

#123 Added changelog file
  CHANGELOG.md
Labels: improvement

#145 Fixing CI
  packages/falcon-server-env/package.json
Labels: automation, bug, node

#134 Codecov
  .travis.yml
  codecov.yml
  package.json
  packages/falcon-client/build-utils/jest/config/create.js
  packages/falcon-magento2-api/package.json
  packages/falcon-server-env/package.json
  packages/falcon-server/package.json
Labels: automation

#78 Google Analytics support
  README.md
  package.json
  packages/create-falcon-app/package.json
  packages/falcon-client/README.md
  packages/falcon-client/docs/ANALYTICS.md
  packages/falcon-client/package.json
  packages/falcon-client/src/components/trackPageView.js
  packages/falcon-client/src/components/withAnalytics.js
  packages/falcon-client/src/components/withPageview.js
  packages/falcon-client/src/graphql/analytics.gql
  scripts/helpers.js
  scripts/new-package.js
Labels: feature, react

#150 [falcon-shop-extension] Fixing GQL Schema
  packages/falcon-shop-extension/src/schema.graphql
Labels: bug, extension, graphql

#178 Create-falcon-app fix (directory check)
  packages/create-falcon-app/src/index.js
Labels: bug, node

#183 Adding "--frozen-lockfile" yarn flag for "nightly builds"
  .gitlab-ci.yml
Labels: automation

#186 fix: Changing Lerna "preid" flag
  .gitlab-ci.yml
Labels: automation, bug

#187 Fixing Lerna tag
  .gitlab-ci.yml
Labels: automation, bug

#173 Apollo config
  examples/shop-with-blog/client/config/default.json
  packages/falcon-client/src/client.js
  packages/falcon-client/src/clientApp/bootstrap.js
  packages/falcon-client/src/clientApp/defaultConfiguration.js
  packages/falcon-client/src/index.js
  packages/falcon-client/src/middlewares/routes/apolloClientProvider.js
  packages/falcon-client/src/middlewares/routes/index.js
  packages/falcon-client/src/server.js
  packages/falcon-client/src/server.test.js
  packages/falcon-client/src/service/ApolloClient.js
  packages/falcon-client/src/service/ApolloClient.test.js
  packages/falcon-client/src/service/apolloStateToObject.js
  packages/falcon-client/src/service/apolloStateToObject.test.js
  packages/falcon-client/src/service/index.js
Labels: improvement

#180 Sign up
  examples/shop-with-blog/client/src/pages/shop/components/Sidebar/SidebarContents.js
  examples/shop-with-blog/client/src/pages/shop/components/Sidebar/SidebarQuery.js
  examples/shop-with-blog/client/src/theme.js
  packages/falcon-ecommerce-uikit/src/Category/Category.tsx
  packages/falcon-ecommerce-uikit/src/Footer/Newsletter.tsx
  packages/falcon-ecommerce-uikit/src/Forms/Form.tsx
  packages/falcon-ecommerce-uikit/src/Forms/FormErrorSummary.tsx
  packages/falcon-ecommerce-uikit/src/Forms/FormField.tsx
  packages/falcon-ecommerce-uikit/src/Forms/FormSubmit.tsx
  packages/falcon-ecommerce-uikit/src/Forms/PasswordRevealInput.tsx
  packages/falcon-ecommerce-uikit/src/Forms/index.ts
  packages/falcon-ecommerce-uikit/src/Forms/validators.ts
  packages/falcon-ecommerce-uikit/src/MiniAccount/MiniAccount.tsx
  packages/falcon-ecommerce-uikit/src/MiniAccount/MiniFormLayout.tsx
  packages/falcon-ecommerce-uikit/src/MiniAccount/SignIn.tsx
  packages/falcon-ecommerce-uikit/src/MiniAccount/SignUp.tsx
  packages/falcon-ecommerce-uikit/src/MiniAccount/index.tsx
  packages/falcon-ecommerce-uikit/src/MiniCart/MiniCart.tsx
  packages/falcon-ecommerce-uikit/src/Product/Product.tsx
  packages/falcon-ecommerce-uikit/src/SignIn/SignInForm.tsx
  packages/falcon-ecommerce-uikit/src/SignUp/SignUpForm.tsx
  packages/falcon-ecommerce-uikit/src/SignUp/SignUpMutation.tsx
  packages/falcon-ecommerce-uikit/src/SignUp/index.ts
  packages/falcon-ecommerce-uikit/src/index.ts
  packages/falcon-magento2-api/src/index.js
  packages/falcon-shop-extension/src/schema.graphql
  packages/falcon-ui/src/theme/theme.ts
Labels: feature
