Repository deity-io/falcon, pull requests merged in 2018-12, with the labels that each got.

#219 Fix ids in address forms on checkout page
  examples/shop-with-blog/client/src/pages/shop/Checkout/AddressSection.js
  examples/shop-with-blog/client/src/pages/shop/Checkout/Checkout.js
  examples/shop-with-blog/client/src/pages/shop/Checkout/CustomerSelector.js
  examples/shop-with-blog/client/src/pages/shop/Checkout/PaymentMethodSection.js
  examples/shop-with-blog/client/src/pages/shop/Checkout/ShippingMethodSection.js
  examples/shop-with-blog/client/src/pages/shop/components/AddressForm.js
Labels: bug

#227 Do not render dropdown's items if the dropdown is closed
  packages/falcon-ui/src/components/Dropdown.tsx
Labels: improvement

#229 Fix error on order confirmation screen
  packages/falcon-magento2-api/src/index.js
Labels: bug

#230 Adding UPGRADE.md file
  CHANGELOG.md
  UPGRADE.md
Labels: docs

#238 Travis CI for pull-requests
  .gitlab-ci.yml
  .travis.yml
  README.md
  packages/falcon-server-env/src/models/ApiDataSource.ts
  packages/falcon-server-env/src/models/Extension.ts
Labels: automation
