Repository deity-io/falcon, pull requests merged in 2019-01, with the labels that each got.

#258 Fixing PORT management for non-development mode
  packages/falcon-client/build-utils/webpack/config/env.js
Labels: bug, node

#146 Make falcon compatible with latest changes in magento module
  CHANGELOG.md
  examples/shop-with-blog/client/src/clientState.js
  examples/shop-with-blog/client/src/pages/Home.js
  examples/shop-with-blog/client/src/pages/shop/Category.js
  examples/shop-with-blog/client/src/pages/shop/Product.js
  packages/falcon-client/src/components/DynamicRoute.js
  packages/falcon-client/src/middlewares/routes/apolloClientProvider.js
  packages/falcon-ecommerce-uikit/src/AppLayout.tsx
  packages/falcon-ecommerce-uikit/src/Blog/BlogPostsLayout.tsx
  packages/falcon-ecommerce-uikit/src/Category/Category.tsx
  packages/falcon-ecommerce-uikit/src/Category/CategoryProductsQuery.tsx
  packages/falcon-ecommerce-uikit/src/Checkout/CheckoutLogic.tsx
  packages/falcon-ecommerce-uikit/src/Product/Product.tsx
  packages/falcon-ecommerce-uikit/src/Product/ProductQuery.tsx
  packages/falcon-ecommerce-uikit/src/SortOrdersProvider.tsx
  packages/falcon-ecommerce-uikit/src/index.ts
  packages/falcon-magento2-api/src/Magento2ApiBase.js
  packages/falcon-magento2-api/src/__mocks__/apiResponses.js
  packages/falcon-magento2-api/src/index.js
  packages/falcon-magento2-api/src/index.test.js
  packages/falcon-server-env/src/models/ApiDataSource.ts
  packages/falcon-server/docs/SchemaStitching.md
  packages/falcon-server/src/schema.graphql
  packages/falcon-shop-extension/src/index.test.js
  packages/falcon-shop-extension/src/schema.graphql
  packages/falcon-ui/src/theme/index.ts
  yarn.lock
Labels: extension, graphql, improvement

#268 Use correct token when fetching product data and breadcrumbs from new api
  packages/falcon-magento2-api/src/index.js
Labels: bug
